<template>
<div class="printlayout">
      <nuxt/>
      <!-- <div class="is-size-5-desktop is-size-6-touch" data-v-aeee610c=""><p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would octish novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciencessh novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciencessh novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novd scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture byst as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novd scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture byst as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
        <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
      <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
      <p>When talking about the relation between the arts and sciencessh novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
      <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
      <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novd scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
      <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture byst as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
      <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
      <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
      <p>When talking about the relation between the arts and sciences, one cannot ignore the ground-breaking lecture by the British novelist and scientist C.P. Snow (1959/1990), in which he criticizes the strong division between what he calls “the two cultures”. Snow concluded that the intellectual life of western society was radically split into two cultures, with the sciences on one side and the arts-humanities on the other. With an eye for detail, he described the different worlds of his scientific and literary friends, who would occasionally peek over the walls of their separation, only to retreat as fast as possible to their own worlds: “there seems to be no place where the cultures meet” (Snow, 1959/1990, p. 172). According to Snow, both parties are not only “self-impoverishing” themselves with this strong division but are also shaping a hindrance to solving the world’s problems. “At the heart of thought and creation we are letting some of our best chances go by default”, he claimed, concluding that “there is only one way out of all this . . . by rethinking our education” (Snow, 1959/1990, p. 172).</p>
      <p>&nbsp;</p>
      </div> -->
</div>
</template>



<script>
import {
  mapGetters
} from 'vuex'


export default {
  // mounted(){
  //   var css = 'html { display: none; }',
  //       head = document.head || document.getElementsByTagName('head')[0],
  //       style = document.createElement('style');
  //
  //   style.type = 'text/css';
  //   if (style.styleSheet){
  //     // This is required for IE8 and below.
  //     style.styleSheet.cssText = css;
  //   } else {
  //     style.appendChild(document.createTextNode(css));
  //   }
  //
  //   head.appendChild(style);
  // }
}
</script>

<style scoped lang="scss">
*{
   // background-color: white;
   overflow: hidden;
}

</style>
